name: Build against Langchain4j main

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.os }} - ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17, 21]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build langchain4j
        run: |
          mkdir langchain4j
          cd langchain4j
          git clone https://github.com/langchain4j/langchain4j.git
          cd langchain4j
          mvn -B clean install -DskipTests

      - name: Build with Maven
        run: mvn -B clean install -Dno-format

      - name: Build with Maven (Native)
        run: mvn -B install -Dnative -Dquarkus.native.container-build -Dnative.surefire.skip
